# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s10:
      dhcp4: true
      addresses: [192.168.64.120/24]
      gateway4: 192.168.64.1
      nameservers: 
        addresses: [8.8.8.8,8.8.4.4]
  version: 2

